### PR TITLE
Add -Wall and -Wextra, fix lots of warnings

### LINKED ISSUE #226: Lots of C/C++ warnings ...
I'm compiling nlopt within an embedded project which has -Wall -Wextra turned on by default and get lots of warnings:

- warning: variable 'xxxx' set but not used [-Wunused-but-set-variable]
- deprecated declaration in f77api.c

I made myself ready to fix them, but now I'm unsure if there is some intention behind these unused variables? If they need to stay in I'd suggest to use `(void) XXX;` to silence the warnings, otherwise I'd remove them, please advise.
For the deprecated functions in f77api.c and f77funcs.h I'd add a GCC pragma (with correct ifdefs) to turn the warning off for these files.

### PR DESCRIPTION
**Pull request by taliesin**
- remove set but not used variables
 - (void) cast unused function arguments
 - create internal function duplicates for some actually
   deprecated functions, for the f77 files disable
   the deprecation warning completely.
 - add warning flags to travis

Note: some of the maybe-unitialized warnings do not
  show in gcc 7.3.0, but travis seems to use a different one.

This closes #226.

### CODE REVIEW

**Comment by taliesin** [comment]
Anything else to be done to have that merged?

File: src/api/nlopt.h [hunk 1]
```diff
@@ -301,12 +301,26 @@ NLOPT_EXTERN(nlopt_result) nlopt_minimize(nlopt_algorithm algorithm, int n, nlop
                                           double *minf, /* out: minimum */
                                           double minf_max, double ftol_rel, double ftol_abs, double xtol_rel, const double *xtol_abs, int maxeval, double maxtime) NLOPT_DEPRECATED;
 
+/* this is still used internally by a few algorithms, it's the same as nlopt_minimize, but without the deprecation */
+NLOPT_EXTERN(nlopt_result) internal_nlopt_minimize(nlopt_algorithm algorithm, int n, nlopt_func_old f, void *f_data,
+                                          const double *lb, const double *ub, /* bounds */
+                                          double *x,    /* in: initial guess, out: minimizer */
+                                          double *minf, /* out: minimum */
+                                          double minf_max, double ftol_rel, double ftol_abs, double xtol_rel, const double *xtol_abs, int maxeval, double maxtime);
+
```
Comment (stevengj) [inline src/api/nlopt.h]: I think it would be better to just update the algorithms to use the new API.

(We shouldn't export an `internal_*` function in `nlopt.h` in any case.)

**Comment by stevengj** [comment]
rebased

File: src/api/nlopt.h (hunk 1 above)
Comment (stevengj) [reply src/api/nlopt.h]: Updated to eliminate these calls.
